"""remove frequency column from chama

Revision ID: 124ed27602f6
Revises: 414dcee0d842
Create Date: 2026-03-15 09:42:38.242998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124ed27602f6'
down_revision = '414dcee0d842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamas', schema=None) as batch_op:
        batch_op.drop_column('frequency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
