"""Add payment_method to ChamaMember

Revision ID: 1df26a98a90a
Revises: e65b6745d033
Create Date: 2026-03-26 18:02:38.468927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df26a98a90a'
down_revision = 'e65b6745d033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chama_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chama_members', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
