"""update product model

Revision ID: 1e5a0d322a9d
Revises: 7e82d1b92235
Create Date: 2026-03-13 09:34:10.660773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e5a0d322a9d'
down_revision = '7e82d1b92235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('cost_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('low_stock', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stock_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('allow_reviews', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lipa_pole_pole', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('chama_eligible', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('length', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('width', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('shipping_class', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('meta_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('meta_keywords', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('meta_keywords')
        batch_op.drop_column('meta_description')
        batch_op.drop_column('meta_title')
        batch_op.drop_column('shipping_class')
        batch_op.drop_column('height')
        batch_op.drop_column('width')
        batch_op.drop_column('length')
        batch_op.drop_column('weight')
        batch_op.drop_column('chama_eligible')
        batch_op.drop_column('lipa_pole_pole')
        batch_op.drop_column('allow_reviews')
        batch_op.drop_column('stock_status')
        batch_op.drop_column('low_stock')
        batch_op.drop_column('cost_price')
        batch_op.drop_column('short_description')

    # ### end Alembic commands ###
