"""updated chama model

Revision ID: 39605a6425a6
Revises: 1e5a0d322a9d
Create Date: 2026-03-14 17:17:48.827314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39605a6425a6'
down_revision = '1e5a0d322a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('target_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('contribution_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('contribution_frequency', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('max_members', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('privacy', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('invite_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cover_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.create_foreign_key(
            "fk_chamas_created_by_users",
            "users",
            ["created_by"],
            ["id"]
        )
        batch_op.drop_column('total_members')
        batch_op.drop_column('monthly_payment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_payment', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('total_members', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('created_by')
        batch_op.drop_column('cover_image')
        batch_op.drop_column('invite_code')
        batch_op.drop_column('privacy')
        batch_op.drop_column('max_members')
        batch_op.drop_column('contribution_frequency')
        batch_op.drop_column('contribution_amount')
        batch_op.drop_column('target_amount')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
