"""add frequency to chama

Revision ID: 414dcee0d842
Revises: 39605a6425a6
Create Date: 2026-03-14 23:44:10.521864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414dcee0d842'
down_revision = '39605a6425a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamas', schema=None) as batch_op:
        batch_op.drop_column('frequency')

    # ### end Alembic commands ###
