"""Add deadline, rules, payment methods, notifications to Chama

Revision ID: cf35de4d1bb0
Revises: 124ed27602f6
Create Date: 2026-03-15 10:11:51.632423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf35de4d1bb0'
down_revision = '124ed27602f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('rules', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('accepts_mpesa', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('accepts_card', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('accepts_bank', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('mpesa_type', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('mpesa_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mpesa_account', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('notify_on_join', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_on_payment', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_on_goal', sa.Boolean(), nullable=True))
        batch_op.alter_column('target_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('contribution_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('privacy',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['invite_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('privacy',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('contribution_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('target_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('notify_on_goal')
        batch_op.drop_column('notify_on_payment')
        batch_op.drop_column('notify_on_join')
        batch_op.drop_column('mpesa_account')
        batch_op.drop_column('mpesa_number')
        batch_op.drop_column('mpesa_type')
        batch_op.drop_column('accepts_bank')
        batch_op.drop_column('accepts_card')
        batch_op.drop_column('accepts_mpesa')
        batch_op.drop_column('rules')
        batch_op.drop_column('deadline')

    # ### end Alembic commands ###
