"""Add payment_method, position, status to ChamaMember

Revision ID: d1e3d0f276ca
Revises: 1df26a98a90a
Create Date: 2026-03-26 18:30:11.410363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e3d0f276ca'
down_revision = '1df26a98a90a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chama_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chama_members', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('position')

    # ### end Alembic commands ###
