"""Add full_name, phone, email, location, address to ChamaMember

Revision ID: e65b6745d033
Revises: c9c3ba8b7019
Create Date: 2026-03-26 17:40:52.062648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65b6745d033'
down_revision = 'c9c3ba8b7019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chama_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chama_members', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('location')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
